server:
  port: 8080

spring:  
  cloud:
    gateway:
      routes:
        - id: usuarioRoute
          uri: lb://DH-USUARIO
          predicates:
           - Path=/usuario/**
        - id: contaRoute
          uri: lb://DH-CONTA
          predicates:
           - Path=/conta/**
          filters:
            - AddRequestHeader=user-request-header, custom-user-request-header
            - AddResponseHeader=user-respons-header, custom-user-response-header 
